blank_lines_lower_bound = 0
brace_style="AlwaysNextLine"
wrap_comments=false
control_brace_style = "AlwaysNextLine"
fn_args_layout = "Compressed"
imports_granularity="Module"
group_imports = "StdExternalCrate"